openapi: 3.0.0
info:
  title: Task Manager API
  description: A simple API to manage tasks (add, update, retrieve, and delete tasks).
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve a list of all tasks.
      responses:
        200:
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Add a new task
      description: Create a new task with a title and description.
      requestBody:
        description: Task object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTask'
      responses:
        201:
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        400:
          description: Invalid input

  /tasks/{task_id}:
    get:
      summary: Get a task by ID
      description: Retrieve a task by its ID.
      parameters:
        - in: path
          name: task_id
          schema:
            type: integer
          required: true
          description: The ID of the task to retrieve
      responses:
        200:
          description: A task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        404:
          description: Task not found
    put:
      summary: Update a task by ID
      description: Update the task's title, description, or status.
      parameters:
        - in: path
          name: task_id
          schema:
            type: integer
          required: true
          description: The ID of the task to update
      requestBody:
        description: Task object with updated details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        200:
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        404:
          description: Task not found
    delete:
      summary: Delete a task by ID
      description: Delete a task from the task manager.
      parameters:
        - in: path
          name: task_id
          schema:
            type: integer
          required: true
          description: The ID of the task to delete
      responses:
        200:
          description: Task deleted successfully
        404:
          description: Task not found

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: The unique ID of the task
        title:
          type: string
          description: The title of the task
        description:
          type: string
          description: The description of the task
        status:
          type: string
          description: The status of the task (e.g., 'Incomplete', 'Complete')

    NewTask:
      type: object
      properties:
        title:
          type: string
          description: The title of the task
          example: "Learn Swagger"
        description:
          type: string
          description: The description of the task
          example: "Write a Swagger file to document the Task Manager API"
